name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-reqtracer
          path: dist/

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-reqtracer
          path: chrome-reqtracer

      - name: Zip extension
        run: zip -r chrome-reqtracer.zip chrome-reqtracer

      - name: Get Date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: untagged-${{ steps.date.outputs.date }}
          body: ${{ github.event.head_commit.message }}
          release_name: untagged-${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chrome-reqtracer.zip
          asset_name: chrome-reqtracer.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
